### ISSUE TITLE
Add news functionality

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal#128]
There should be support for news entries on the landing page. They must include:

- Authoring user (taken from the admin backend login)
- Date of creation
- Text
- Priority (levels are defined by @DenizCankurtaran )

**Comment by DenizCankurtaran** [comment]
I have thought of 3 solutions for the priority.
They could either be

1.  Numbers varying from 0 to 2, where 0 would be low- and 2 high-priority and I would change the icon based on the number
2.  Icons, since I use https://materialdesignicons.com/ we could pick 3 icons and have their name send from the backend 
3.  Colors, priority could be green, orange or red and I would use the same icon but with a different priority color

**Comment by troeger** [comment]
Closed via #139
